{% set name = "analyticsdf" %}
{% set version = "0.0.4.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ea16d2af2f16d14edff9ec04d27cbf75579455a48260e0425d5dd6c71243c42e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pandas
    - pip
    - python
    - scipy
  run:
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - analyticsdf

about:
  home: "https://github.com/Faye-yufan/analytics-dataset"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Analytic generation of datasets with specified statistical characteristics."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
